#eureka:
#  instance:
#    prefer-ip-address: true #注册使用ip
#    instance-id: 192.168.8.51:${ConfigCenter.port} #实例id
#    ip-address: 192.168.8.51 #可访问的ip地址

spring:
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
    #配置中心
    config:
      server:
        git:
          uri: https://github.com/lianshufeng/MicroService.git
          search-paths: centers/ApplicationCenter/Config/src/main/resources/config/**
          force-pull: true
          skip-ssl-validation: true
#          proxy:
#            https:
#              host: 127.0.0.1
#              port: 808
#            http:
#              host: 127.0.0.1
#              port: 808
#          username: aiyihema
#          password: aiyihema

