build:
  task:
    core-project: IT/MicroService
  git:
    type: Gogs
    core: MicroService
    host: http://192.168.20.222:3000/
    userName: stdc
    passWord: CPMBf0Dq95SPxcKU
    token: c07c442a10d159c37f4dee26d14fdd6e08e6fccc
  maven:
    home: "D:/sdk/apache-maven-3.8.7"
