spring:
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
  data:
    mongodb:
      uri: mongodb://auth:auth@192.168.31.132:27017,192.168.31.132:27018/auth
      auto-index-creation: true
    redis:
      host: 192.168.31.132
      port: 6379
      database: 2
      password: redis_passwd_2024



init:
  client:
    - clientId: test
      secret: 123456
      authorizedGrantTypes: client_credentials,password,refresh_token
  organizations:
    - name: test_platform
      authType: Platform
      remark: 默认创建平台
      roleGroup:
        - name: roleGroupName
          identity: identityName
          remark: 角色组
          role:
            - name: roleName
              remark: 角色
              auth:
                - auth1
                - auth2
                - test1
                - test2
          user:
            - loginType: Phone
              loginValue: 15123241353
              passWord: xiaofeng
            - loginType: Phone
              loginValue: 15123241363
              passWord: xiaoxue





springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  swagger-ui:
    # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
    persistAuthorization: true


#logging:
#  level:
#    org:
#      springframework:
#        web: trace
#debug: true
#trace: true

logging:
  level:
    com:
      github:
        microservice:
          core:
            runner: debug

#    org.springframework.security: trace